/* Seguimiento Preventivo 2026 - GitHub Pages */
const COLORS={mpas:'#16a34a',great:'#2563eb',municipal:'#f97316',both:'#7e22ce',danger:'#dc2626'};
const COORD={
'CARMEN':[9.9365,-84.0750],'MERCED':[9.9386,-84.0828],'HOSPITAL':[9.9274,-84.0918],'CATEDRAL':[9.9289,-84.0740],'ZAPOTE':[9.9198,-84.0553],'SAN FRANCISCO':[9.9136,-84.0724],'URUCA':[9.9567,-84.1060],'MATA REDONDA':[9.9352,-84.1047],'PAVAS':[9.9488,-84.1342],'HATILLO':[9.9160,-84.1010],'SAN SEBASTIAN':[9.9121,-84.0909],'ESCAZU':[9.9180,-84.1399],'SANTA ANA':[9.9326,-84.1825],'ALAJUELITA':[9.9016,-84.1],'VASQUEZ DE CORONADO':[9.976,-84.007],'CORONADO':[9.976,-84.007],'ACOSTA':[9.8003,-84.1604],'TIBAS':[9.958,-84.079],'MORAVIA':[9.961,-84.048],'MONTES DE OCA':[9.9369,-84.05],'CURRIDABAT':[9.9136,-84.0405],'GOICOECHEA':[9.948,-84.043],'DESAMPARADOS':[9.8982,-84.0626],'ASERRI':[9.8587,-84.0917],'MORA':[9.9182,-84.2411],'PURISCAL':[9.8469,-84.3149],'TARRAZU':[9.6596,-84.0206],'DOTA':[9.65,-83.96],'LEON CORTES':[9.683,-84.05],'TURRUBARES':[9.905,-84.452],'ALAJUELA':[10.0162,-84.2116],'SAN RAMON':[10.0887,-84.4702],'GRECIA':[10.0739,-84.3112],'SAN MATEO':[9.9365,-84.5247],'ATENAS':[9.9787,-84.3801],'NARANJO':[10.0987,-84.3782],'PALMARES':[10.0567,-84.437],'POAS':[10.08,-84.245],'OROTINA':[9.9111,-84.523],'SAN CARLOS':[10.329,-84.431],'ZARCERO':[10.1852,-84.39],'SARCHI':[10.0883,-84.3473],'UPALA':[10.8986,-85.0155],'LOS CHILES':[11.035,-84.713],'GUATUSO':[10.6667,-84.8167],'RIO CUARTO':[10.341,-84.214],'CARTAGO':[9.8644,-83.9194],'PARAISO':[9.8383,-83.8656],'LA UNION':[9.9084,-83.9886],'JIMENEZ':[9.9048,-83.6834],'TURRIALBA':[9.905,-83.683],'ALVARADO':[9.9333,-83.8],'OREAMUNO':[9.91,-83.9],'EL GUARCO':[9.8472,-83.946],'HEREDIA':[10.0024,-84.1165],'BARVA':[10.0208,-84.1233],'SANTO DOMINGO':[10.0639,-84.1547],'SANTA BARBARA':[10.04,-84.16],'SAN RAFAEL':[10.0138,-84.1002],'SAN ISIDRO':[10.0186,-84.0569],'BELEN':[9.9852,-84.181],'FLORES':[10,-84.16],'SAN PABLO':[9.9953,-84.0966],'SARAPIQUI':[10.4522,-84.0166],'LIBERIA':[10.635,-85.4377],'NICOYA':[10.1483,-85.452],'SANTA CRUZ':[10.26,-85.585],'BAGACES':[10.525,-85.255],'CARRILLO':[10.475,-85.585],'CANAS':[10.431,-85.098],'ABANGARES':[10.282,-84.959],'TILARAN':[10.467,-84.967],'NANDAYURE':[9.999,-85.206],'LA CRUZ':[11.073,-85.632],'HOJANCHA':[10.055,-85.42],'PUNTARENAS':[9.9763,-84.8384],'CHOMES':[10.095,-84.925],'JUDAS':[10.051,-84.887],'ESPARZA':[9.994,-84.664],'BUENOS AIRES':[9.1667,-83.3333],'MONTES DE ORO':[10.087,-84.73],'OSA':[8.959,-83.523],'QUEPOS':[9.4319,-84.1617],'GOLFITO':[8.639,-83.166],'COTO BRUS':[8.883,-82.966],'PARRITA':[9.52,-84.32],'CORREDORES':[8.642,-82.946],'GARABITO':[9.615,-84.63],'LIMON':[9.9917,-83.036],'POCOCI':[10.215,-83.787],'SIQUIRRES':[10.097,-83.506],'TALAMANCA':[9.624,-82.844],'MATINA':[10.076,-83.289],'GUACIMO':[10.21,-83.69],'PEREZ ZELEDON':[9.354,-83.634],'LOS SANTOS':[9.655,-84.03]};
const PROV={'SAN JOSE':[9.9281,-84.0907],'ALAJUELA':[10.0162,-84.2116],'CARTAGO':[9.8644,-83.9194],'HEREDIA':[10.0024,-84.1165],'GUANACASTE':[10.635,-85.4377],'PUNTARENAS':[9.9763,-84.8384],'LIMON':[9.9917,-83.036]};

const state={files:{mep:null,mpas:null,great:null},mep:[],mpas:[],greatFP:[],municipal:[],totals:{mpas:emptyTotals(),great:emptyTotals(),municipal:emptyTotals()},view:null,filters:{region:'Todas',province:'Todas',canton:'Todos',district:'Todos',activity:'Todos'},map:null,markers:null,currentRows:[],currentTable:[]};
function emptyTotals(){return{centros:0,primaria:0,intermedia:0,ninos:0}}
const $=id=>document.getElementById(id);
function norm(v){if(v===null||v===undefined)return'';return String(v).trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').toUpperCase()}
function normCode(v){if(v===null||v===undefined)return'';return String(v).trim().replace(/\.0$/,'').replace(/[^0-9A-Za-z]/g,'').toUpperCase()}
function num(v){const n=Number(String(v??'').replace(/,/g,''));return Number.isFinite(n)?n:0}
function fmt(n){return new Intl.NumberFormat('es-CR').format(Math.round(n||0))}
function pct(n){return `${(n||0).toFixed(1)}%`}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2600)}
function showLoading(v){$('loading').classList.toggle('hidden',!v)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function detectHeader(rows){const keys=['PROVINCIA','CANTON','DISTRITO','CENTRO EDUCATIVO','INSTITUCION','CODIGO MEP','CODIGO PRESUPUESTARIO'];let best=0,score=-1;for(let i=0;i<Math.min(20,rows.length);i++){const s=(rows[i]||[]).map(norm).join(' | ');const p=keys.filter(k=>s.includes(k)).length;if(p>score){best=i;score=p}}return best}
function findCol(headers,ops){const normalized=headers.map(h=>[h,norm(h)]), wanted=ops.map(norm);for(const [h,n] of normalized)if(wanted.includes(n))return h;for(const [h,n] of normalized)if(wanted.some(x=>x&&(n.includes(x)||x.includes(n))))return h;return null}
async function readWorkbook(file){const buffer=await file.arrayBuffer();const wb=XLSX.read(buffer,{type:'array',cellDates:true});return wb}
function sheetRows(wb,name){const real=wb.SheetNames.find(n=>norm(n)===norm(name));if(!real)return[];return XLSX.utils.sheet_to_json(wb.Sheets[real],{header:1,defval:null,raw:false})}
function readAllSheets(wb){const out=[];for(const sheetName of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{header:1,defval:null,raw:false});if(!rows.some(r=>r.some(v=>v!==null&&String(v).trim()!=='')))continue;const hi=detectHeader(rows);const headers=(rows[hi]||[]).map((v,i)=>String(v??`COL_${i}`).trim()||`COL_${i}`);for(let r=hi+1;r<rows.length;r++){const row=rows[r]||[];if(!row.some(v=>v!==null&&String(v).trim()!==''))continue;const obj={HOJA_ORIGEN:sheetName};headers.forEach((h,i)=>obj[h]=row[i]??null);out.push(obj)}}return out}
function readTotals(wb,sheetName){const rows=sheetRows(wb,sheetName);if(!rows.length)return emptyTotals();const labels={'TOTAL ESCUELAS':'centros','TOTAL CENTROS':'centros','TOTAL PRIMARIA':'primaria','TOTAL INTERMEDIA':'intermedia','TOTAL NINOS':'ninos'};const candidates={centros:[],primaria:[],intermedia:[],ninos:[]};for(const row of rows){for(let j=0;j<row.length;j++){const label=norm(row[j]);if(!labels[label])continue;const key=labels[label];for(let q=j+1;q<Math.min(j+9,row.length);q++){const n=num(row[q]);if(Number.isFinite(n)){candidates[key].push(n);break}}}}return Object.fromEntries(Object.entries(candidates).map(([k,v])=>[k,v.length?Math.max(...v):0]))}

function prepareMEP(all){if(!all.length)return[];const headers=Object.keys(all[0]);const ci=findCol(headers,['Institución','Institucion','Nombre del centro educativo','Escuela']);const cp=findCol(headers,['Provincia']);const cc=findCol(headers,['Cantón','Canton']);const cd=findCol(headers,['Distrito']);const ck=findCol(headers,['Código presupuestario','Codigo presupuestario','Código MEP','Codigo MEP']);if(!ci||!cp||!cc||!cd)throw new Error('La base MEP no contiene Institución, Provincia, Cantón y Distrito.');const out=[];for(const d of all){const centro=String(d[ci]??'').trim(),provincia=String(d[cp]??'').trim(),canton=String(d[cc]??'').trim(),distrito=String(d[cd]??'').trim();if(!centro||!provincia||!canton||!distrito||norm(centro).startsWith('TOTAL'))continue;const r={REGION_MEP:String(d.HOJA_ORIGEN??'').trim(),CENTRO_MEP:centro,PROVINCIA:provincia,CANTON:canton,DISTRITO:distrito,CODIGO_MEP:ck?d[ck]:''};r.REGION_MEP_N=norm(r.REGION_MEP);r.PROVINCIA_N=norm(provincia);r.CANTON_N=norm(canton);r.DISTRITO_N=norm(distrito);r.CENTRO_MEP_N=norm(centro);r.CODIGO_N=normCode(r.CODIGO_MEP);r.ID_FILA_MEP=String(out.length);r.ID_NOMBRE=`${r.PROVINCIA_N}|${r.CANTON_N}|${r.DISTRITO_N}|${r.CENTRO_MEP_N}`;out.push(r)}return out}
function prepareProgram(all,sheet,source,group){const q=all.filter(d=>norm(d.HOJA_ORIGEN)===norm(sheet));if(!q.length)return[];const headers=[...new Set(q.flatMap(Object.keys))];const cn=findCol(headers,['Nombre del centro educativo','Institución','Escuela']);const ck=findCol(headers,['Código MEP','Codigo MEP']);const cp=findCol(headers,['Provincia']);const cc=findCol(headers,['Cantón','Canton']);const cd=findCol(headers,['Distrito']);const cr=findCol(headers,['Región','Region']);const c1=findCol(headers,['Primaria']);const c2=findCol(headers,['Intermedia']);const ct=findCol(headers,['Total niños capacitados','Total ninos capacitados','Cantidad de niños','Cantidad ninos','Niños','Ninos']);if(!cn||!ct)return[];const out=[];for(const d of q){const centro=String(d[cn]??'').trim();if(!centro||/TOTAL NINOS|TOTAL ESCUELAS|TOTAL CENTROS/.test(norm(centro)))continue;out.push({FUENTE:source,GRUPO:group,CENTRO_ORIGEN:centro,CODIGO_ORIGINAL:ck?d[ck]:'',PROVINCIA_ORIGEN:cp?String(d[cp]??'').trim():'',CANTON_ORIGEN:cc?String(d[cc]??'').trim():'',DISTRITO_ORIGEN:cd?String(d[cd]??'').trim():'',REGION_ORIGEN:cr?String(d[cr]??'').trim():'',PRIMARIA:c1?num(d[c1]):0,INTERMEDIA:c2?num(d[c2]):0,NINOS:num(d[ct]),CODIGO_N:normCode(ck?d[ck]:''),CENTRO_ORIGEN_N:norm(centro)})}return out}
function detailTotals(d){return{centros:d.length,primaria:d.reduce((a,x)=>a+x.PRIMARIA,0),intermedia:d.reduce((a,x)=>a+x.INTERMEDIA,0),ninos:d.reduce((a,x)=>a+x.NINOS,0)}}

function tokenSort(s){return norm(s).split(' ').filter(Boolean).sort().join(' ')}
function levenshtein(a,b){a=tokenSort(a);b=tokenSort(b);const m=a.length,n=b.length;if(!m)return n;if(!n)return m;let prev=Array.from({length:n+1},(_,i)=>i);for(let i=1;i<=m;i++){const cur=[i];for(let j=1;j<=n;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=cur}return prev[n]}
function similarity(a,b){const A=tokenSort(a),B=tokenSort(b),mx=Math.max(A.length,B.length);return mx?1-levenshtein(A,B)/mx:1}
function relate(mep,detail){if(!detail.length)return[];if(!mep.length)return detail.map(d=>{const r={...d,CENTRO_MEP:d.CENTRO_ORIGEN,REGION_MEP:d.REGION_ORIGEN||d.FUENTE,PROVINCIA:d.PROVINCIA_ORIGEN,CANTON:d.CANTON_ORIGEN,DISTRITO:d.DISTRITO_ORIGEN,ID_FILA_MEP:null,COINCIDENCIA:'Base MEP no cargada'};r.PROVINCIA_N=norm(r.PROVINCIA);r.CANTON_N=norm(r.CANTON);r.DISTRITO_N=norm(r.DISTRITO);r.ID_NOMBRE=`${r.PROVINCIA_N}|${r.CANTON_N}|${r.DISTRITO_N}|${r.CENTRO_ORIGEN_N}`;r.UBICADO=!!(r.PROVINCIA_N&&r.CANTON_N&&r.DISTRITO_N);return r});const byCode=new Map();for(const m of mep)if(m.CODIGO_N&&!byCode.has(m.CODIGO_N))byCode.set(m.CODIGO_N,m);return detail.map(d=>{let m=byCode.get(d.CODIGO_N),match='Código MEP / presupuestario';if(!m){let best=null,bestScore=0;for(const x of mep){const s=similarity(d.CENTRO_ORIGEN_N,x.CENTRO_MEP_N);if(s>bestScore){best=x;bestScore=s}}if(bestScore>=.92){m=best;match=`Revisión por nombre (${Math.round(bestScore*100)}%)`}else match='No localizado'}if(m)return{...d,...pick(m,['ID_FILA_MEP','ID_NOMBRE','CENTRO_MEP','REGION_MEP','PROVINCIA','CANTON','DISTRITO','PROVINCIA_N','CANTON_N','DISTRITO_N']),COINCIDENCIA:match,UBICADO:true};const r={...d,CENTRO_MEP:d.CENTRO_ORIGEN,REGION_MEP:d.REGION_ORIGEN,PROVINCIA:d.PROVINCIA_ORIGEN,CANTON:d.CANTON_ORIGEN,DISTRITO:d.DISTRITO_ORIGEN,ID_FILA_MEP:null,COINCIDENCIA:match};r.PROVINCIA_N=norm(r.PROVINCIA);r.CANTON_N=norm(r.CANTON);r.DISTRITO_N=norm(r.DISTRITO);r.ID_NOMBRE=`${r.PROVINCIA_N}|${r.CANTON_N}|${r.DISTRITO_N}|${r.CENTRO_ORIGEN_N}`;r.UBICADO=!!(r.PROVINCIA_N&&r.CANTON_N&&r.DISTRITO_N);return r})}
function pick(o,ks){return Object.fromEntries(ks.map(k=>[k,o[k]]))}
function getCoord(d,c,p){for(const k of [d,c])if(COORD[k])return COORD[k];return PROV[p]||[9.7489,-83.7534]}
function summarize(mep,activity){if(mep.length){const grouped=new Map();for(const m of mep){const key=[m.REGION_MEP,m.PROVINCIA,m.CANTON,m.DISTRITO,m.PROVINCIA_N,m.CANTON_N,m.DISTRITO_N].join('¦');if(!grouped.has(key))grouped.set(key,{REGION_MEP:m.REGION_MEP,PROVINCIA:m.PROVINCIA,CANTON:m.CANTON,DISTRITO:m.DISTRITO,PROVINCIA_N:m.PROVINCIA_N,CANTON_N:m.CANTON_N,DISTRITO_N:m.DISTRITO_N,INSTITUCIONES_MEP:0,CENTROS_ACTIVOS:0,NINOS:0});grouped.get(key).INSTITUCIONES_MEP++}const acts=new Map();for(const a of activity.filter(x=>x.UBICADO)){const key=[a.REGION_MEP,a.PROVINCIA,a.CANTON,a.DISTRITO].join('¦');if(!acts.has(key))acts.set(key,{ids:new Set(),ninos:0});acts.get(key).ids.add(a.ID_NOMBRE);acts.get(key).ninos+=a.NINOS}const out=[];for(const z of grouped.values()){const a=acts.get([z.REGION_MEP,z.PROVINCIA,z.CANTON,z.DISTRITO].join('¦'));if(a){z.CENTROS_ACTIVOS=a.ids.size;z.NINOS=a.ninos}const [lat,lon]=getCoord(z.DISTRITO_N,z.CANTON_N,z.PROVINCIA_N);z.LAT=lat;z.LON=lon;out.push(z)}return out}else{const grouped=new Map();for(const a of activity.filter(x=>x.UBICADO)){const key=[a.REGION_MEP,a.PROVINCIA,a.CANTON,a.DISTRITO].join('¦');if(!grouped.has(key))grouped.set(key,{REGION_MEP:a.REGION_MEP,PROVINCIA:a.PROVINCIA,CANTON:a.CANTON,DISTRITO:a.DISTRITO,PROVINCIA_N:norm(a.PROVINCIA),CANTON_N:norm(a.CANTON),DISTRITO_N:norm(a.DISTRITO),INSTITUCIONES_MEP:null,ids:new Set(),NINOS:0});const z=grouped.get(key);z.ids.add(a.ID_NOMBRE);z.NINOS+=a.NINOS}return [...grouped.values()].map(z=>{z.CENTROS_ACTIVOS=z.ids.size;delete z.ids;const [lat,lon]=getCoord(z.DISTRITO_N,z.CANTON_N,z.PROVINCIA_N);z.LAT=lat;z.LON=lon;return z})}}
function groupedCenters(rows){const map=new Map();for(const a of rows){if(!map.has(a.ID_NOMBRE))map.set(a.ID_NOMBRE,{ID_NOMBRE:a.ID_NOMBRE,REGION_MEP:a.REGION_MEP,PROVINCIA:a.PROVINCIA,CANTON:a.CANTON,DISTRITO:a.DISTRITO,CENTRO_MEP:a.CENTRO_MEP,CODIGO_N:a.CODIGO_N,PRIMARIA:0,INTERMEDIA:0,NINOS:0,sources:new Set(),groups:new Set()});const z=map.get(a.ID_NOMBRE);z.PRIMARIA+=a.PRIMARIA;z.INTERMEDIA+=a.INTERMEDIA;z.NINOS+=a.NINOS;z.sources.add(a.FUENTE);z.groups.add(a.GRUPO)}return [...map.values()].map(z=>({...z,FUENTES:[...z.sources].sort().join(' + '),GRUPOS:[...z.groups].sort().join(' + ')}))}

function updateFileUI(kind,file){const el=$(kind==='mep'?'mepStatus':kind==='mpas'?'mpasStatus':'greatStatus');if(file){el.className='file-status ready';el.textContent=`✓ ${file.name}`;state.files[kind]=file}else{el.className='file-status empty';el.textContent='No cargado';state.files[kind]=null}const count=Object.values(state.files).filter(Boolean).length;$('processBtn').disabled=!count;$('loadHint').textContent=count?`${count} archivo${count>1?'s':''} listo${count>1?'s':''} para procesar.`:'Carga al menos un archivo para iniciar.'}
['mep','mpas','great'].forEach(kind=>$(kind+'File').addEventListener('change',e=>updateFileUI(kind,e.target.files[0]||null)));
$('resetBtn').addEventListener('click',()=>location.reload());
$('processBtn').addEventListener('click',processFiles);
$('clearFiltersBtn').addEventListener('click',()=>{state.filters={region:'Todas',province:'Todas',canton:'Todos',district:'Todos',activity:'Todos'};renderDashboard()});
$('downloadBtn').addEventListener('click',downloadCSV);

async function processFiles(){showLoading(true);try{state.mep=[];state.mpas=[];state.greatFP=[];state.municipal=[];state.totals={mpas:emptyTotals(),great:emptyTotals(),municipal:emptyTotals()};let mepWB=null,mpasWB=null,greatWB=null;if(state.files.mep){mepWB=await readWorkbook(state.files.mep);state.mep=prepareMEP(readAllSheets(mepWB))}if(state.files.mpas){mpasWB=await readWorkbook(state.files.mpas);const detail=prepareProgram(readAllSheets(mpasWB),'MPAS','MPAS','MPAS');state.mpas=relate(state.mep,detail);state.totals.mpas=readTotals(mpasWB,'MPAS');if(!state.totals.mpas.centros)state.totals.mpas=detailTotals(detail)}if(state.files.great){greatWB=await readWorkbook(state.files.great);const all=readAllSheets(greatWB);const dg=prepareProgram(all,'GREAT','GREAT Fuerza Pública','GREAT');const dp=prepareProgram(all,'POLICIA MUNICIPAL','Policía Municipal','GREAT');state.greatFP=relate(state.mep,dg);state.municipal=relate(state.mep,dp);state.totals.great=readTotals(greatWB,'GREAT');if(!state.totals.great.centros)state.totals.great=detailTotals(dg);state.totals.municipal=readTotals(greatWB,'POLICIA MUNICIPAL');if(!state.totals.municipal.centros)state.totals.municipal=detailTotals(dp)}buildViewOptions();$('dashboard').classList.remove('hidden');renderLoadedBadges();renderDashboard();setTimeout(()=>$('dashboard').scrollIntoView({behavior:'smooth',block:'start'}),120);toast('Información procesada correctamente')}catch(err){console.error(err);toast(`Error: ${err.message}`)}finally{showLoading(false)}}
function sourceDatasets(){return[state.mpas,state.greatFP,state.municipal].filter(x=>x.length)}
function buildViewOptions(){const opts=[];const sources=sourceDatasets();if(sources.length>=2)opts.push('Todos los datos cargados');if(state.mpas.length)opts.push('MPAS');if(state.greatFP.length)opts.push('GREAT Fuerza Pública');if(state.municipal.length)opts.push('Policía Municipal');if(state.greatFP.length&&state.municipal.length)opts.push('GREAT unificado');if(state.mpas.length&&(state.greatFP.length||state.municipal.length))opts.push('MPAS y GREAT en el mismo centro');if(!opts.length&&state.mep.length)opts.push('Base MEP');state.view=opts[0]||null;renderPills('viewPills',opts,state.view,v=>{state.view=v;state.filters.activity='Todos';renderDashboard()})}
function renderLoadedBadges(){const b=[];if(state.mep.length)b.push(`<span class="source-badge mep">MEP · ${fmt(state.mep.length)}</span>`);if(state.mpas.length)b.push(`<span class="source-badge mpas">MPAS · ${fmt(state.mpas.length)}</span>`);if(state.greatFP.length)b.push(`<span class="source-badge great">GREAT · ${fmt(state.greatFP.length)}</span>`);if(state.municipal.length)b.push(`<span class="source-badge municipal">Municipal · ${fmt(state.municipal.length)}</span>`);$('loadedBadges').innerHTML=b.join('')}
function renderPills(id,options,active,onClick){const el=$(id);el.innerHTML='';for(const o of options){const b=document.createElement('button');b.type='button';b.textContent=o;b.classList.toggle('active',o===active);b.onclick=()=>onClick(o);el.appendChild(b)}}
function activityRows(){const greatTotal=[...state.greatFP,...state.municipal],all=[...state.mpas,...greatTotal];switch(state.view){case'MPAS':return[...state.mpas];case'GREAT Fuerza Pública':return[...state.greatFP];case'Policía Municipal':return[...state.municipal];case'GREAT unificado':return greatTotal;case'MPAS y GREAT en el mismo centro':{const ids=new Set(state.mpas.map(x=>x.ID_NOMBRE));const both=new Set(greatTotal.filter(x=>ids.has(x.ID_NOMBRE)).map(x=>x.ID_NOMBRE));return all.filter(x=>both.has(x.ID_NOMBRE))}case'Todos los datos cargados':return all;default:return[]}}
function territorialFilter(summary){let f=[...summary];if(state.filters.region!=='Todas')f=f.filter(x=>x.REGION_MEP===state.filters.region);if(state.filters.province!=='Todas')f=f.filter(x=>x.PROVINCIA===state.filters.province);if(state.filters.canton!=='Todos')f=f.filter(x=>x.CANTON===state.filters.canton);if(state.filters.district!=='Todos')f=f.filter(x=>x.DISTRITO===state.filters.district);return f}
function filterActivityRows(rows){return rows.filter(x=>(state.filters.region==='Todas'||x.REGION_MEP===state.filters.region)&&(state.filters.province==='Todas'||x.PROVINCIA===state.filters.province)&&(state.filters.canton==='Todos'||x.CANTON===state.filters.canton)&&(state.filters.district==='Todos'||x.DISTRITO===state.filters.district))}
function setupSelect(id,values,current,allLabel,onChange){const el=$(id);el.innerHTML='';const all=document.createElement('option');all.value=allLabel;all.textContent=allLabel;el.appendChild(all);for(const v of values){const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)}if([...el.options].some(o=>o.value===current))el.value=current;else{el.value=allLabel;current=allLabel}el.onchange=()=>onChange(el.value);return current}
function renderFilters(summary){const base=[...summary];const regions=uniq(base.map(x=>x.REGION_MEP));state.filters.region=setupSelect('regionFilter',regions,state.filters.region,'Todas',v=>{state.filters.region=v;state.filters.province='Todas';state.filters.canton='Todos';state.filters.district='Todos';renderDashboard()});let f=state.filters.region==='Todas'?base:base.filter(x=>x.REGION_MEP===state.filters.region);state.filters.province=setupSelect('provinceFilter',uniq(f.map(x=>x.PROVINCIA)),state.filters.province,'Todas',v=>{state.filters.province=v;state.filters.canton='Todos';state.filters.district='Todos';renderDashboard()});if(state.filters.province!=='Todas')f=f.filter(x=>x.PROVINCIA===state.filters.province);state.filters.canton=setupSelect('cantonFilter',uniq(f.map(x=>x.CANTON)),state.filters.canton,'Todos',v=>{state.filters.canton=v;state.filters.district='Todos';renderDashboard()});if(state.filters.canton!=='Todos')f=f.filter(x=>x.CANTON===state.filters.canton);state.filters.district=setupSelect('districtFilter',uniq(f.map(x=>x.DISTRITO)),state.filters.district,'Todos',v=>{state.filters.district=v;renderDashboard()});const acts=state.mep.length?['Todos','Con actividad','Sin actividad']:['Todos','Con actividad'];if(!acts.includes(state.filters.activity))state.filters.activity='Todos';renderPills('activityPills',acts,state.filters.activity,v=>{state.filters.activity=v;renderDashboard()})}
function uniq(a){return [...new Set(a.filter(v=>v!==null&&v!==undefined&&String(v).trim()))].sort((a,b)=>String(a).localeCompare(String(b),'es'))}
function nationalView(){return state.filters.region==='Todas'&&state.filters.province==='Todas'&&state.filters.canton==='Todos'&&state.filters.district==='Todos'}
function metricsFor(territorial,centers){const nm=state.mep.length?territorial.reduce((a,x)=>a+x.INSTITUCIONES_MEP,0):null;let cent=centers.length,pri=centers.reduce((a,x)=>a+x.PRIMARIA,0),inter=centers.reduce((a,x)=>a+x.INTERMEDIA,0),nin=centers.reduce((a,x)=>a+x.NINOS,0);if(nationalView()){let t=null;if(state.view==='MPAS')t=state.totals.mpas;if(state.view==='GREAT Fuerza Pública')t=state.totals.great;if(state.view==='Policía Municipal')t=state.totals.municipal;if(t){cent=t.centros;pri=t.primaria;inter=t.intermedia;nin=t.ninos}}if(state.view==='Base MEP'){cent=pri=inter=nin=0}const cov=nm?cent/nm*100:null;return{nm,cent,pri,inter,nin,cov}}
function renderMetrics(m){const cards=[['Instituciones MEP',m.nm===null?'No cargada':fmt(m.nm),'Universo territorial','#64748b'],['Centros visibles',fmt(m.cent),'Centros según selección',programColor()],['Primaria',fmt(m.pri),'Participación reportada','#0ea5e9'],['Intermedia',fmt(m.inter),'Participación reportada','#6366f1'],['Total niños',fmt(m.nin),'Impacto acumulado','#f59e0b'],['Cobertura',m.cov===null?'—':pct(m.cov),'Sobre universo MEP','#0f172a']];$('metricGrid').innerHTML=cards.map(c=>`<article class="metric-card" style="--metric:${c[3]}"><div class="metric-label">${c[0]}</div><div class="metric-value">${c[1]}</div><div class="metric-foot">${c[2]}</div></article>`).join('')}
function programColor(){if(state.view==='MPAS')return COLORS.mpas;if(state.view==='GREAT Fuerza Pública')return COLORS.great;if(state.view==='Policía Municipal')return COLORS.municipal;if(state.view==='MPAS y GREAT en el mismo centro')return COLORS.both;return'#334155'}
function renderSummary(m){const universe=m.nm===null?'sin base MEP cargada':`${fmt(m.nm)} instituciones MEP`;$('summaryTitle').textContent=state.view;$('summaryText').innerHTML=`Se visualizan <b>${fmt(m.cent)} centros</b> y <b>${fmt(m.nin)} niños reportados</b> dentro de ${universe}.${m.cov===null?' La cobertura requiere cargar la base MEP.':` Cobertura territorial: <b>${pct(m.cov)}</b>.`}`}
function renderInsights(m,centers){const sources=new Map();for(const c of centers)for(const s of c.FUENTES.split(' + '))sources.set(s,(sources.get(s)||0)+1);const items=[['Centros visibles',fmt(m.cent),'Selección actual'],['Niños reportados',fmt(m.nin),'Suma de la selección'],['Distritos activos',fmt(new Set(centers.map(x=>`${x.PROVINCIA}|${x.CANTON}|${x.DISTRITO}`)).size),'Con al menos un centro'],...([...sources.entries()].slice(0,3).map(([k,v])=>[k,fmt(v),'Centros asociados']))];$('insights').innerHTML=items.map(i=>`<div class="insight-item"><span>${esc(i[0])}</span><strong>${esc(i[1])}</strong><small>${esc(i[2])}</small></div>`).join('')}
function sourceType(sources){const fs=sources.split(' + ');if(fs.length>1)return'both';if(fs.includes('MPAS'))return'mpas';if(fs.includes('Policía Municipal'))return'municipal';return'great'}
function renderLegend(){const keys=[];const allSources=[...state.mpas,...state.greatFP,...state.municipal];if(allSources.some(x=>x.FUENTE==='MPAS'))keys.push(['MPAS',COLORS.mpas]);if(allSources.some(x=>x.FUENTE==='GREAT Fuerza Pública'))keys.push(['GREAT Fuerza Pública',COLORS.great]);if(allSources.some(x=>x.FUENTE==='Policía Municipal'))keys.push(['Policía Municipal',COLORS.municipal]);if(sourceDatasets().length>1)keys.push(['Más de una fuente',COLORS.both]);if(state.mep.length)keys.push(['Sin actividad',COLORS.danger]);$('mapLegend').innerHTML=keys.map(k=>`<span class="map-key"><i style="background:${k[1]}"></i>${k[0]}</span>`).join('')}
function initMap(){if(state.map)return;state.map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([9.7489,-83.7534],8);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'&copy; OpenStreetMap contributors &copy; CARTO',maxZoom:19}).addTo(state.map);state.markers=L.layerGroup().addTo(state.map)}
function pinIcon(n,type){return L.divIcon({className:'',html:`<div class="custom-pin pin-${type}">${n}</div>`,iconSize:[34,34],iconAnchor:[17,17]})}
function renderMap(territorial,centers){initMap();const mapEl=$('map');mapEl.classList.add('map-refresh');setTimeout(()=>mapEl.classList.remove('map-refresh'),230);state.markers.clearLayers();renderLegend();let mapRows=[...territorial];if(state.filters.activity==='Con actividad')mapRows=mapRows.filter(x=>x.CENTROS_ACTIVOS>0);if(state.filters.activity==='Sin actividad')mapRows=mapRows.filter(x=>x.CENTROS_ACTIVOS===0);const bounds=[];if(state.mep.length&&(state.filters.activity==='Todos'||state.filters.activity==='Sin actividad'))for(const q of mapRows.filter(x=>x.CENTROS_ACTIVOS===0)){const m=L.marker([q.LAT,q.LON],{icon:pinIcon('×','none')}).bindTooltip(`${esc(q.DISTRITO)} · Sin actividad`).bindPopup(`<b>${esc(q.DISTRITO)}</b><br>Sin actividad para: ${esc(state.view)}<br>Provincia: ${esc(q.PROVINCIA)}<br>Cantón: ${esc(q.CANTON)}<br>Instituciones MEP: ${fmt(q.INSTITUCIONES_MEP)}`);state.markers.addLayer(m);bounds.push([q.LAT,q.LON])}let visibleCenters=state.filters.activity==='Sin actividad'?[]:centers;if(visibleCenters.length){const groups=new Map();for(const q of visibleCenters){const [lat,lon]=getCoord(norm(q.DISTRITO),norm(q.CANTON),norm(q.PROVINCIA));const key=`${lat.toFixed(6)}|${lon.toFixed(6)}`;if(!groups.has(key))groups.set(key,{lat,lon,rows:[]});groups.get(key).rows.push(q)}let number=1;for(const g of groups.values()){const count=g.rows.length;g.rows.forEach((q,pos)=>{let lat=g.lat,lon=g.lon;if(count>1){const ring=Math.floor(pos/8),pa=pos%8,elements=Math.min(8,count-ring*8),ang=2*Math.PI*pa/Math.max(elements,1),radius=.009+ring*.007;lat+=radius*Math.cos(ang);lon+=radius*Math.sin(ang)}const type=sourceType(q.FUENTES);const popup=`<div style="min-width:250px"><b>${number}. ${esc(q.CENTRO_MEP)}</b><br><span style="color:${COLORS[type]||COLORS.both};font-weight:700">${esc(q.FUENTES)}</span><hr style="border:0;border-top:1px solid #e2e8f0"><b>Código MEP:</b> ${esc(q.CODIGO_N)}<br><b>Región:</b> ${esc(q.REGION_MEP)}<br><b>Provincia:</b> ${esc(q.PROVINCIA)}<br><b>Cantón:</b> ${esc(q.CANTON)}<br><b>Distrito:</b> ${esc(q.DISTRITO)}<br><b>Primaria:</b> ${fmt(q.PRIMARIA)}<br><b>Intermedia:</b> ${fmt(q.INTERMEDIA)}<br><b>Total niños:</b> ${fmt(q.NINOS)}</div>`;const m=L.marker([lat,lon],{icon:pinIcon(number,type),zIndexOffset:1000+number}).bindTooltip(`${number}. ${esc(q.CENTRO_MEP)} · ${esc(q.FUENTES)}`).bindPopup(popup);state.markers.addLayer(m);bounds.push([lat,lon]);number++})}$('pinCount').textContent=`${fmt(visibleCenters.length)} pines`}else $('pinCount').textContent='0 pines';if(bounds.length)state.map.fitBounds(bounds,{padding:[28,28],maxZoom:13,animate:true,duration:.55});else state.map.setView([9.7489,-83.7534],8,{animate:true});setTimeout(()=>state.map.invalidateSize(),80)}
function sourceChip(v){const type=sourceType(v);return `<span class="source-chip ${type}">${esc(v)}</span>`}
function renderTable(centers){if(state.view==='Base MEP'){let rows=[...state.mep];if(state.filters.region!=='Todas')rows=rows.filter(x=>x.REGION_MEP===state.filters.region);if(state.filters.province!=='Todas')rows=rows.filter(x=>x.PROVINCIA===state.filters.province);if(state.filters.canton!=='Todos')rows=rows.filter(x=>x.CANTON===state.filters.canton);if(state.filters.district!=='Todos')rows=rows.filter(x=>x.DISTRITO===state.filters.district);state.currentTable=rows.map(r=>({'Región MEP':r.REGION_MEP,'Provincia':r.PROVINCIA,'Cantón':r.CANTON,'Distrito':r.DISTRITO,'Institución':r.CENTRO_MEP,'Código presupuestario':r.CODIGO_N}));$('tableTitle').textContent='Instituciones MEP';renderHTMLTable(state.currentTable);return}if(state.filters.activity==='Sin actividad'){state.currentTable=[];$('tableTitle').textContent='Centros abordados';renderHTMLTable([],'La vista “Sin actividad” no contiene centros abordados.');return}state.currentTable=centers.map(r=>({Fuente:r.FUENTES,Región:r.REGION_MEP,Provincia:r.PROVINCIA,Cantón:r.CANTON,Distrito:r.DISTRITO,'Centro educativo':r.CENTRO_MEP,'Código MEP':r.CODIGO_N,Primaria:r.PRIMARIA,Intermedia:r.INTERMEDIA,'Total niños':r.NINOS}));$('tableTitle').textContent='Centros abordados';renderHTMLTable(state.currentTable)}
function renderHTMLTable(rows,emptyMsg='No hay registros para los filtros seleccionados.'){const thead=$('dataTable').querySelector('thead'),tbody=$('dataTable').querySelector('tbody');$('rowCount').textContent=`${fmt(rows.length)} registros`;if(!rows.length){thead.innerHTML='';tbody.innerHTML=`<tr><td style="padding:28px;text-align:center;color:#94a3b8">${emptyMsg}</td></tr>`;return}const cols=Object.keys(rows[0]);thead.innerHTML=`<tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr>`;tbody.innerHTML=rows.map(r=>`<tr>${cols.map(c=>`<td>${c==='Fuente'?sourceChip(r[c]):esc(typeof r[c]==='number'?fmt(r[c]):r[c])}</td>`).join('')}</tr>`).join('')}
function renderPending(){if(!state.mep.length){$('pendingPanel').classList.add('hidden');return}const all=sourceDatasets().flat();const p=all.filter(x=>x.COINCIDENCIA==='No localizado');if(!p.length){$('pendingPanel').classList.add('hidden');return}$('pendingPanel').classList.remove('hidden');$('pendingCount').textContent=fmt(p.length);$('pendingBody').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Fuente</th><th>Centro</th><th>Código</th><th>Niños</th><th>Estado</th></tr></thead><tbody>${p.map(x=>`<tr><td>${sourceChip(x.FUENTE)}</td><td>${esc(x.CENTRO_ORIGEN)}</td><td>${esc(x.CODIGO_N)}</td><td>${fmt(x.NINOS)}</td><td>${esc(x.COINCIDENCIA)}</td></tr>`).join('')}</tbody></table></div>`}
function downloadCSV(){if(!state.currentTable.length){toast('No hay datos para descargar');return}const cols=Object.keys(state.currentTable[0]);const csv=[cols,...state.currentTable.map(r=>cols.map(c=>String(r[c]??'').replace(/"/g,'""')))].map(row=>row.map(v=>`"${v}"`).join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='centros_filtrados.csv';a.click();URL.revokeObjectURL(url)}
function renderDashboard(){const act=activityRows(),summary=summarize(state.mep,act);renderFilters(summary);const territorial=territorialFilter(summary);const fa=filterActivityRows(act);const centers=groupedCenters(fa);const m=metricsFor(territorial,centers);renderMetrics(m);renderSummary(m);renderInsights(m,centers);renderMap(territorial,centers);renderTable(centers);renderPending()}
